sudo: required


services:
  - docker

before_install:
  - docker build -t 1528280/docker-angular -f Dockerfile.dev .


script:
  - timeout --preserve-status 30s docker run -e CI=true 1528280/docker-angular npm run test

